name: Deploy CV

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Обновили Node.js до 24
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build

      - name: Prepare Clean Production Build
        run: |
          mkdir build
          cp src/index.html build/index.html
          sed -i 's|\.\./dist/output.css|./dist/output.css|g' build/index.html
          cp -r dist build/
          cp src/*.png build/ 2>/dev/null || true
          cp src/*.jpg build/ 2>/dev/null || true
          cp src/*.svg build/ 2>/dev/null || true
          cp src/*.ico build/ 2>/dev/null || true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
